import { App, Stack } from "aws-cdk-lib";
import * as batch from "aws-cdk-lib/aws-batch";
import { Secret } from "aws-cdk-lib/aws-secretsmanager";
import {
  ChatTemplateContentFormat,
  ConfigFormat,
  DataType,
  Device,
  DistributedExecutorBackend,
  GuidedDecodingBackend,
  KvCacheDtype,
  LoadFormat,
  LoraDtype,
  ModelImpl,
  PreemptionMode,
  PrefixCachingHashAlgo,
  Quantization,
  ReasoningParser,
  SchedulingPolicy,
  TokenizerMode,
  ToolCallParser,
  UvicornLogLevel,
  VllmEngineArguments,
  VllmEngineArgumentsParser,
  VllmTask,
} from "./vllm-engine-argments";

describe("VllmEngineArgumentsToConfig", () => {
  const app = new App();
  const stack = new Stack(app);
  const secret = Secret.fromSecretNameV2(
    stack,
    "DummySecret",
    "huggingface-token",
  );
  it("should convert all camelCase properties to kebab-case", () => {
    const testObj: VllmEngineArguments = {
      host: "localhost",
      port: 8080,
      uvicornLogLevel: UvicornLogLevel.INFO,
      disableUvicornAccessLog: true,
      allowCredentials: true,
      allowedOrigins: ["*"],
      allowedMethods: ["GET"],
      allowedHeaders: ["Authorization"],
      apiKey: "secret",
      loraModules: { name: "name", path: "lora_path", base_model_name: "id" },
      promptAdapters: ["adapter=path"],
      chatTemplate: "template.json",
      chatTemplateContentFormat: ChatTemplateContentFormat.AUTO,
      responseRole: "assistant",
      sslKeyfile: "key.pem",
      sslCertfile: "cert.pem",
      sslCaCerts: "ca.pem",
      enableSslRefresh: true,
      sslCertReqs: 1,
      rootPath: "/api",
      middleware: ["middleware1"],
      returnTokensAsTokenIds: true,
      disableFrontendMultiprocessing: true,
      enableRequestIdHeaders: true,
      enableAutoToolChoice: true,
      toolCallParser: ToolCallParser.GRANITE,
      toolParserPlugin: "plugin",
      model: "model-name",
      task: VllmTask.GENERATE,
      tokenizer: "tokenizer-name",
      hfConfigPath: "config.json",
      skipTokenizerInit: true,
      revision: "v1.0",
      codeRevision: "v2.0",
      tokenizerRevision: "v1.5",
      tokenizerMode: TokenizerMode.AUTO,
      trustRemoteCode: true,
      allowedLocalMediaPath: "/media",
      configFormat: ConfigFormat.HF,
      dtype: DataType.FLOAT16,
      maxModelLen: 2048,
      logitsProcessorPattern: "pattern",
      modelImpl: ModelImpl.VLLM,
      disableSlidingWindow: true,
      useV2BlockManager: true,
      seed: 42,
      maxLogprobs: 10,
      disableLogStats: true,
      quantization: Quantization.AWQ,
      ropeScaling: {},
      ropeTheta: 1.0,
      hfToken: batch.Secret.fromSecretsManager(secret),
      hfOverrides: {},
      enforceEager: true,
      maxSeqLenToCapture: 4096,
      mmProcessorKwargs: {},
      disableMmPreprocessorCache: true,
      enableLora: true,
      enableLoraBias: true,
      maxLoras: 2,
      maxLoraRank: 32,
      loraExtraVocabSize: 512,
      loraDtype: LoraDtype.FLOAT16,
      longLoraScalingFactors: 1,
      maxCpuLoras: 4,
      fullyShardedLoras: true,
      enablePromptAdapter: true,
      maxPromptAdapters: 2,
      maxPromptAdapterToken: 256,
      numSchedulerSteps: 2,
      speculativeConfig: {},
      ignorePatterns: ["pattern"],
      preemptionMode: PreemptionMode.SWAP,
      servedModelName: ["model1"],
      qloraAdapterNameOrPath: "qlora",
      showHiddenMetricsForVersion: "0.5",
      otlpTracesEndpoint: "http://localhost",
      collectDetailedTraces: "modules",
      disableAsyncOutputProc: true,
      maxNumBatchedTokens: 512,
      maxNumSeqs: 16,
      maxNumPartialPrefills: 4,
      maxLongPartialPrefills: 2,
      longPrefillTokenThreshold: 256,
      numLookaheadSlots: 4,
      schedulerDelayFactor: 0.5,
      enableChunkedPrefill: true,
      multiStepStreamOutputs: false,
      schedulingPolicy: SchedulingPolicy.PRIORITY,
      disableChunkedMmInput: true,
      schedulerCls: "custom.Scheduler",
      overrideNeuronConfig: {},
      overridePoolerConfig: {},
      compilationConfig: {},
      kvTransferConfig: {},
      workerCls: "CustomWorker",
      workerExtensionCls: "Extension",
      generationConfig: "config",
      overrideGenerationConfig: {},
      enableSleepMode: true,
      additionalConfig: {},
      enableReasoning: true,
      disableCascadeAttn: true,
      disableLogRequests: true,
      maxLogLen: 100,
      disableFastApiDocs: true,
      enablePromptTokensDetails: true,
      enableServerLoadTracking: true,
      loadFormat: LoadFormat.SAFETENSORS,
      downloadDir: "/downloads",
      modelLoaderExtraConfig: {},
      useTqdmOnLoad: false,
      guidedDecodingBackend: GuidedDecodingBackend.OUTLINES,
      reasoningParser: ReasoningParser.DEEPSEEK_R1,
      distributedExecutorBackend: DistributedExecutorBackend.RAY,
      pipelineParallelSize: 2,
      tensorParallelSize: 2,
      dataParallelSize: 2,
      enableExpertParallel: true,
      maxParallelLoadingWorkers: 4,
      rayWorkersUseNsight: true,
      disableCustomAllReduce: true,
      blockSize: 16,
      gpuMemoryUtilization: 0.8,
      swapSpace: 8,
      kvCacheDtype: KvCacheDtype.FP8,
      numGpuBlocksOverride: 16,
      enablePrefixCaching: true,
      prefixCachingHashAlgo: PrefixCachingHashAlgo.SHA256,
      cpuOffloadGb: 2,
      calculateKvScales: true,
      limitMmPerPrompt: {},
      device: Device.NEURON,
    };

    const result = VllmEngineArgumentsParser.config(testObj);

    expect(result).toMatchObject({
      host: "localhost",
      port: 8080,
      "uvicorn-log-level": "info",
      "disable-uvicorn-access-log": true,
      "allow-credentials": true,
      "allowed-origins": '["*"]',
      "allowed-methods": '["GET"]',
      "allowed-headers": '["Authorization"]',
      "api-key": "secret",
      "lora-modules":
        '{"name":"name","path":"lora_path","base_model_name":"id"}',
      "prompt-adapters": ["adapter=path"],
      "chat-template": "template.json",
      "chat-template-content-format": "auto",
      "response-role": "assistant",
      "ssl-keyfile": "key.pem",
      "ssl-certfile": "cert.pem",
      "ssl-ca-certs": "ca.pem",
      "enable-ssl-refresh": true,
      "ssl-cert-reqs": 1,
      "root-path": "/api",
      middleware: ["middleware1"],
      "return-tokens-as-token-ids": true,
      "disable-frontend-multiprocessing": true,
      "enable-request-id-headers": true,
      "enable-auto-tool-choice": true,
      "tool-call-parser": "granite",
      "tool-parser-plugin": "plugin",
      // should ignore the model property
      // model: "model-name",
      task: "generate",
      tokenizer: "tokenizer-name",
      // should ignore the hf-token property
      // "hf-token": "dummy",
      "hf-config-path": "config.json",
      "skip-tokenizer-init": true,
      revision: "v1.0",
      "code-revision": "v2.0",
      "tokenizer-revision": "v1.5",
      "tokenizer-mode": "auto",
      "trust-remote-code": true,
      "allowed-local-media-path": "/media",
      "config-format": "hf",
      dtype: "float16",
      "max-model-len": 2048,
      "logits-processor-pattern": "pattern",
      "model-impl": "vllm",
      "disable-sliding-window": true,
      "use-v2-block-manager": true,
      seed: 42,
      "max-logprobs": 10,
      "disable-log-stats": true,
      quantization: "awq",
      "rope-scaling": "{}",
      "rope-theta": 1.0,
      "hf-overrides": "{}",
      "enforce-eager": true,
      "max-seq-len-to-capture": 4096,
      "mm-processor-kwargs": "{}",
      "disable-mm-preprocessor-cache": true,
      "enable-lora": true,
      "enable-lora-bias": true,
      "max-loras": 2,
      "max-lora-rank": 32,
      "lora-extra-vocab-size": 512,
      "lora-dtype": "float16",
      "long-lora-scaling-factors": 1,
      "max-cpu-loras": 4,
      "fully-sharded-loras": true,
      "enable-prompt-adapter": true,
      "max-prompt-adapters": 2,
      "max-prompt-adapter-token": 256,
      "num-scheduler-steps": 2,
      "speculative-config": "{}",
      "ignore-patterns": ["pattern"],
      "preemption-mode": "swap",
      "served-model-name": ["model1"],
      "qlora-adapter-name-or-path": "qlora",
      "show-hidden-metrics-for-version": "0.5",
      "otlp-traces-endpoint": "http://localhost",
      "collect-detailed-traces": "modules",
      "disable-async-output-proc": true,
      "max-num-batched-tokens": 512,
      "max-num-seqs": 16,
      "max-num-partial-prefills": 4,
      "max-long-partial-prefills": 2,
      "long-prefill-token-threshold": 256,
      "num-lookahead-slots": 4,
      "scheduler-delay-factor": 0.5,
      "enable-chunked-prefill": true,
      "multi-step-stream-outputs": false,
      "scheduling-policy": "priority",
      "disable-chunked-mm-input": true,
      "scheduler-cls": "custom.Scheduler",
      "override-neuron-config": "{}",
      "override-pooler-config": "{}",
      "compilation-config": "{}",
      "kv-transfer-config": "{}",
      "worker-cls": "CustomWorker",
      "worker-extension-cls": "Extension",
      "generation-config": "config",
      "override-generation-config": "{}",
      "enable-sleep-mode": true,
      "additional-config": "{}",
      "enable-reasoning": true,
      "disable-cascade-attn": true,
      "disable-log-requests": true,
      "max-log-len": 100,
      "disable-fast-api-docs": true,
      "enable-prompt-tokens-details": true,
      "enable-server-load-tracking": true,
      "load-format": "safetensors",
      "download-dir": "/downloads",
      "model-loader-extra-config": "{}",
      "use-tqdm-on-load": false,
      "guided-decoding-backend": "outlines",
      "reasoning-parser": "deepseek_r1",
      "distributed-executor-backend": "ray",
      "pipeline-parallel-size": 2,
      "tensor-parallel-size": 2,
      "data-parallel-size": 2,
      "enable-expert-parallel": true,
      "max-parallel-loading-workers": 4,
      "ray-workers-use-nsight": true,
      "disable-custom-all-reduce": true,
      "block-size": 16,
      "gpu-memory-utilization": 0.8,
      "swap-space": 8,
      "kv-cache-dtype": "fp8",
      "num-gpu-blocks-override": 16,
      "enable-prefix-caching": true,
      "prefix-caching-hash-algo": "sha256",
      "cpu-offload-gb": 2,
      "calculate-kv-scales": true,
      "limit-mm-per-prompt": "{}",
      device: "neuron",
    });
  });
});
